apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-iris-workload
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-iris-workload
  template:
    metadata:
      labels:
        app: demo-iris-workload
    spec:
      containers:
        - name: iris-api
          image: us-central1-docker.pkg.dev/operating-edge-473204-j5/my-repo/iris-api:latest
          ports:
            - containerPort: 8200
          resources:
            requests:
              cpu: "0.1"
              memory: "128Mi"
            limits:
              cpu: "0.2"
              memory: "256Mi"
