apiVersion: v1
kind: Service
metadata:
  name: demo-iris-workload-service
spec:
  selector:
    app: demo-iris-workload
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8200
  type: LoadBalancer
